#!/bin/bash
# Ubuntu VM Deployment Script for Secure AI Chat v1.0.1
# This script prepares an Ubuntu VM for production deployment

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔═══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Secure AI Chat v1.0.2 - Ubuntu VM Deployment            ║${NC}"
echo -e "${BLUE}╚═══════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Configuration
REPO_URL="https://github.com/mazh-cp/secure-ai-chat.git"
REPO_DIR="/home/adminuser/secure-ai-chat"
BRANCH="release/v1.0.2"
NODE_VERSION="25.2.1"
SERVICE_NAME="secure-ai-chat"
SERVICE_USER="adminuser"
SERVICE_GROUP="adminuser"

# Step 1: Update OS packages
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Step 1: Update OS packages${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install -y git curl ca-certificates ripgrep

echo -e "${GREEN}✅ OS packages updated${NC}"
echo ""

# Step 2: Install Node.js LTS (Node 25.2.1)
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Step 2: Install Node.js ${NODE_VERSION}${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Check if nvm is installed
if [ ! -d "$HOME/.nvm" ]; then
    echo "Installing NVM..."
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
fi

# Install Node.js version
source "$HOME/.nvm/nvm.sh" || true
nvm install ${NODE_VERSION}
nvm use ${NODE_VERSION}
nvm alias default ${NODE_VERSION}

# Verify Node.js installation
NODE_VER=$(node -v)
NPM_VER=$(npm -v)
echo -e "${GREEN}✅ Node.js ${NODE_VER} installed${NC}"
echo -e "${GREEN}✅ npm ${NPM_VER} installed${NC}"
echo ""

# Step 3: Clone repository
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Step 3: Clone repository${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

if [ -d "$REPO_DIR" ]; then
    echo "Repository already exists, updating..."
    cd "$REPO_DIR"
    git fetch origin
    git checkout ${BRANCH}
    git pull origin ${BRANCH}
else
    echo "Cloning repository..."
    mkdir -p "$(dirname "$REPO_DIR")"
    git clone -b ${BRANCH} ${REPO_URL} ${REPO_DIR}
    cd "$REPO_DIR"
fi

echo -e "${GREEN}✅ Repository cloned/updated to ${BRANCH}${NC}"
echo ""

# Step 4: Install dependencies
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Step 4: Install dependencies${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Set Node.js version for this session
source "$HOME/.nvm/nvm.sh" 2>/dev/null || true
export PATH="$HOME/.nvm/versions/node/v${NODE_VERSION}/bin:$PATH"

cd "$REPO_DIR"
npm ci

echo -e "${GREEN}✅ Dependencies installed${NC}"
echo ""

# Step 5: Create production environment file
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Step 5: Create production environment file${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

if [ ! -f "$REPO_DIR/.env" ]; then
    tee "$REPO_DIR/.env" > /dev/null <<EOF
# Secure AI Chat v1.0.2 Production Configuration
# Generated by deploy-ubuntu-vm.sh

# Application
NODE_ENV=production
PORT=3000

# Optional: Check Point ThreatCloud / Threat Emulation API Key
# Can be set here or via Settings UI
# CHECKPOINT_TE_API_KEY=your_api_key_here

# Optional: Encryption key for API key storage (if not set, uses default)
# CHECKPOINT_TE_ENCRYPTION_KEY=your_encryption_key_here

# Security
# Note: API keys can be configured via Settings UI after deployment
EOF
    chmod 600 "$REPO_DIR/.env"
    echo -e "${GREEN}✅ Production environment file created${NC}"
else
    echo -e "${YELLOW}⚠️  Environment file already exists, skipping${NC}"
fi
echo ""

# Step 6: Build application
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Step 6: Build application${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

cd "$REPO_DIR"
npm run build

echo -e "${GREEN}✅ Application built successfully${NC}"
echo ""

# Step 7: Set permissions
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Step 7: Set permissions${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

chown -R ${SERVICE_USER}:${SERVICE_GROUP} "$REPO_DIR"
chmod -R 755 "$REPO_DIR"
chmod 600 "$REPO_DIR/.env" 2>/dev/null || true
chmod 700 "$REPO_DIR/.secure-storage" 2>/dev/null || true

echo -e "${GREEN}✅ Permissions set${NC}"
echo ""

# Step 8: Create systemd service
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Step 8: Create systemd service${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Source Node.js from nvm if available
if [ -f "$HOME/.nvm/nvm.sh" ]; then
    source "$HOME/.nvm/nvm.sh"
    nvm use ${NODE_VERSION} || nvm alias default ${NODE_VERSION}
fi

NODE_PATH=$(which node || echo "/home/adminuser/.nvm/versions/node/v${NODE_VERSION}/bin/node")
NPM_PATH=$(which npm || echo "/home/adminuser/.nvm/versions/node/v${NODE_VERSION}/bin/npm")

# Ensure Node.js is in PATH
export PATH="$(dirname "$NODE_PATH"):$PATH"

sudo tee "/etc/systemd/system/${SERVICE_NAME}.service" > /dev/null <<EOF
[Unit]
Description=Secure AI Chat Application
After=network.target

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_GROUP}
WorkingDirectory=${REPO_DIR}
Environment=NODE_ENV=production
Environment=PATH=${NODE_PATH%/*}:/usr/local/bin:/usr/bin:/bin
EnvironmentFile=${REPO_DIR}/.env
# Use npm start to handle Next.js server
ExecStart=${NPM_PATH} start
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=secure-ai-chat

# Security
NoNewPrivileges=true
PrivateTmp=true
ReadWritePaths=${REPO_DIR}/.secure-storage ${REPO_DIR}/.next

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
echo -e "${GREEN}✅ Systemd service created${NC}"
echo ""

# Step 9: Enable and start service
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Step 9: Enable and start service${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

sudo systemctl enable ${SERVICE_NAME}
sudo systemctl start ${SERVICE_NAME}

# Wait a moment for service to start
sleep 3

# Check service status
if sudo systemctl is-active --quiet ${SERVICE_NAME}; then
    echo -e "${GREEN}✅ Service started successfully${NC}"
else
    echo -e "${RED}❌ Service failed to start${NC}"
    sudo systemctl status ${SERVICE_NAME} --no-pager -l
    exit 1
fi
echo ""

# Step 10: Verification
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Step 10: Verification${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

echo "Service status:"
sudo systemctl status ${SERVICE_NAME} --no-pager -l | head -15
echo ""

echo "Health check:"
if curl -s http://localhost:3000/api/health > /dev/null; then
    echo -e "${GREEN}✅ Health endpoint responding${NC}"
    curl -s http://localhost:3000/api/health | head -3
else
    echo -e "${RED}❌ Health endpoint not responding${NC}"
fi
echo ""

echo -e "${GREEN}╔═══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║              ✅ DEPLOYMENT COMPLETE                           ║${NC}"
echo -e "${GREEN}║                                                               ║${NC}"
echo -e "${GREEN}║  Application is running on http://localhost:3000             ║${NC}"
echo -e "${GREEN}║  Service: ${SERVICE_NAME}                                      ║${NC}"
echo -e "${GREEN}║  Branch: ${BRANCH}                           ║${NC}"
echo -e "${GREEN}║                                                               ║${NC}"
echo -e "${GREEN}║  Next steps:                                                 ║${NC}"
echo -e "${GREEN}║  1. Configure Check Point TE API key via Settings UI         ║${NC}"
echo -e "${GREEN}║  2. Configure other API keys via Settings UI                 ║${NC}"
echo -e "${GREEN}║  3. Set up PIN for API key protection (optional)             ║${NC}"
echo -e "${GREEN}║  4. Test file sandboxing with Check Point TE                 ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════════════╝${NC}"
echo ""

echo "Useful commands:"
echo "  sudo systemctl status ${SERVICE_NAME}"
echo "  sudo systemctl restart ${SERVICE_NAME}"
echo "  sudo journalctl -u ${SERVICE_NAME} -f"
echo ""
